Prototipo.Curso.MVC.Web/Models/EstadoViewModel.cs
using Prototipo.Curso.MVC.Dominio.Modelos;

namespace Prototipo.Curso.MVC.Web.Models
{
    public class EstadoViewModel
    {
        public EstadoViewModel(Estado estado = null)
        {
            if (estado != null)
            {
                EstadoId = estado.Id;
                NomeEstado = estado.NomeEstado;
            }
        }

        public int EstadoId { get; set; }
        public string NomeEstado { get; set; }

        public Estado ToEstado(IFormCollection collection)
        {
            var estado = new Estado();

            if (!String.IsNullOrEmpty(collection["EstadoId"].ToString()))
            {
                estado.Id = Convert.ToInt32(collection["EstadoId"]);
            }

            estado.NomeEstado = collection["NomeEstado"].ToString();

            return estado;
        }
    }
}

Prototipo.Curso.MVC.Web/Controllers/CidadeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prototipo.Curso.MVC.Dados.Interfaces;
using Prototipo.Curso.MVC.Dominio.Modelos;
using Prototipo.Curso.MVC.Web.Models;

namespace Prototipo.Curso.MVC.Web.Controllers
{
    public class CidadeController : Controller
    {
        private readonly ICidadeRepository _cidadeRepository;
        private readonly IEstadoRepository _estadoRepository;

        public CidadeController(ICidadeRepository cidadeRepository,
                                IEstadoRepository estadoRepository)
        {
            _cidadeRepository = cidadeRepository;
            _estadoRepository = estadoRepository;
        }

        // GET: CidadeController
        public ActionResult Index()
        {
            var cidades = _cidadeRepository.GetAll();
            var cidadeViewModelList = new List<CidadeViewModel>();

            foreach (var cidade in cidades)
                cidadeViewModelList.Add(new CidadeViewModel(cidade));

            return View(cidadeViewModelList);
        }

        // GET: CidadeController/Details/5
        public ActionResult Details(int id)
        {
            var cidade = _cidadeRepository.GetById(id);
            var cidadeViewModel = new CidadeViewModel(cidade);

            return View(cidadeViewModel);
        }

        // GET: CidadeController/Create
        public ActionResult Create()
        {
            GetEstadosViewModel();

            return View();
        }

        // POST: CidadeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var cidadeViewModel = new CidadeViewModel();
                var cidade = cidadeViewModel.ToCidade(collection);

                _cidadeRepository.Create(cidade);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CidadeController/Edit/5
        public ActionResult Edit(int id)
        {
            var cidade = _cidadeRepository.GetById(id);
            var cidadeViewModel = new CidadeViewModel(cidade);

            GetEstadosViewModel();

            return View(cidadeViewModel);
        }

        // POST: CidadeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var cidadeViewModel = new CidadeViewModel();
                var cidade = cidadeViewModel.ToCidade(collection);
                _cidadeRepository.Update(cidade);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private void GetEstadosViewModel()
        {
            var estados = _estadoRepository.GetAll();
            var estadoViewModelList = new List<EstadoViewModel>();

            foreach (var estado in estados)
                estadoViewModelList.Add(new EstadoViewModel(estado));

            ViewBag.estadoViewModelList = new MultiSelectList(estadoViewModelList, "EstadoId", "NomeEstado");
        }

    }
}

Prototipo.Curso.MVC.Web/Controllers/EstadoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prototipo.Curso.MVC.Dados.Interfaces;
using Prototipo.Curso.MVC.Dominio.Modelos;
using Prototipo.Curso.MVC.Web.Models;

namespace Prototipo.Curso.MVC.Web.Controllers
{
    public class EstadoController : Controller
    {
        private readonly IEstadoRepository _estadoRepository;

        public EstadoController(IEstadoRepository estadoRepository)
        {
            _estadoRepository = estadoRepository;
        }

        // GET: EstadoController
        public ActionResult Index()
        {
            var estados = _estadoRepository.GetAll();
            var estadoViewModelList = new List<EstadoViewModel>();

            foreach (var estado in estados)
                estadoViewModelList.Add(new EstadoViewModel(estado));

            return View(estadoViewModelList);
        }

        // GET: EstadoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EstadoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var estadoViewModel = new EstadoViewModel();
                var estado = estadoViewModel.ToEstado(collection);

                _estadoRepository.Create(estado);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EstadoController/Edit/5
        public ActionResult Edit(int id)
        {
            var estado = _estadoRepository.GetById(id);
            var estadoViewModel = new EstadoViewModel(estado);

            return View(estadoViewModel);
        }

        // POST: EstadoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var estadoViewModel = new EstadoViewModel();
                var estado = estadoViewModel.ToEstado(collection);

                _estadoRepository.Update(estado);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Prototipo.Curso.MVC.Web/Views/Estado/Create.cshtml
@model Prototipo.Curso.MVC.Web.Models.EstadoViewModel

@{
    ViewData["Title"] = "Novo Estado";
}

<h2>Novo Estado</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeEstado" class="control-label">Nome Estado</label>
                <input asp-for="NomeEstado" class="form-control" />
                <span asp-validation-for="NomeEstado" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Enviar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à listagem</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prototipo.Curso.MVC.Web/Views/Estado/Edit.cshtml
@model Prototipo.Curso.MVC.Web.Models.EstadoViewModel

@{
    ViewData["Title"] = "Edição";
}

<h2>Edição Estado</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input hidden asp-for="EstadoId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NomeEstado" class="control-label"></label>
                <input asp-for="NomeEstado" class="form-control" />
                <span asp-validation-for="NomeEstado" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à listagem</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prototipo.Curso.MVC.Web/Views/Estado/Index.cshtml
@model IEnumerable<Prototipo.Curso.MVC.Web.Models.EstadoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Novo Estado</a> | <a asp-controller="Cidade" asp-action="Index">Voltar p/ Cidades</a>s
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Estado
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeEstado)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { Id = item.EstadoId })
                </td>
            </tr>
        }
    </tbody>
</table>