Prototipo.Curso.MVC.Web/Models/CidadeViewModel.cs
using Prototipo.Curso.MVC.Dominio.Modelos;

namespace Prototipo.Curso.MVC.Web.Models
{
    public class CidadeViewModel
    {
        public CidadeViewModel(Cidade cidade = null)
        {
            if (cidade != null)
            {
                CidadeId = cidade.Id;
                NomeCidade = cidade.NomeCidade;
                EstadoViewModel = new EstadoViewModel(cidade.Estado);
                EstadoId = cidade.EstadoId;
            }
        }

        public int CidadeId { get; set; }
        public string NomeCidade { get; set; }
        public virtual EstadoViewModel EstadoViewModel { get; set; }
        public int EstadoId { get; set; }

        public Cidade ToCidade(IFormCollection colletcion)
        {
            var cidade = new Cidade();

            if (!String.IsNullOrEmpty(colletcion["CidadeId"].ToString()))
            {
                cidade.Id = Convert.ToInt32(colletcion["CidadeId"]);
            }

            cidade.NomeCidade = colletcion["NomeCidade"].ToString();
            cidade.EstadoId = Convert.ToInt32(colletcion["EstadoId"]);

            return cidade;
        }

    }
}

Prototipo.Curso.MVC.Web/Controllers/CidadeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Prototipo.Curso.MVC.Dados.Interfaces;
using Prototipo.Curso.MVC.Dominio.Modelos;
using Prototipo.Curso.MVC.Web.Models;

namespace Prototipo.Curso.MVC.Web.Controllers
{
    public class CidadeController : Controller
    {
        private readonly ICidadeRepository _cidadeRepository;
        private readonly IEstadoRepository _estadoRepository;

        public CidadeController(ICidadeRepository cidadeRepository,
                                IEstadoRepository estadoRepository)
        {
            _cidadeRepository = cidadeRepository;
            _estadoRepository = estadoRepository;
        }

        // GET: CidadeController
        public ActionResult Index()
        {
            var cidades = _cidadeRepository.GetAll();
            var cidadeViewModelList = new List<CidadeViewModel>();

            foreach (var cidade in cidades)
                cidadeViewModelList.Add(new CidadeViewModel(cidade));

            return View(cidadeViewModelList);
        }

        // GET: CidadeController/Details/5
        public ActionResult Details(int id)
        {
            var cidade = _cidadeRepository.GetById(id);
            var cidadeViewModel = new CidadeViewModel(cidade);

            return View(cidadeViewModel);
        }

        // GET: CidadeController/Create
        public ActionResult Create()
        {
            GetEstadosViewModel();

            return View();
        }

        // POST: CidadeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var cidadeViewModel = new CidadeViewModel();
                var cidade = cidadeViewModel.ToCidade(collection);

                _cidadeRepository.Create(cidade);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CidadeController/Edit/5
        public ActionResult Edit(int id)
        {
            var cidade = _cidadeRepository.GetById(id);
            var cidadeViewModel = new CidadeViewModel(cidade);

            GetEstadosViewModel();

            return View(cidadeViewModel);
        }

        // POST: CidadeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var cidadeViewModel = new CidadeViewModel();
                var cidade = cidadeViewModel.ToCidade(collection);
                _cidadeRepository.Update(cidade);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private void GetEstadosViewModel()
        {
            var estados = _estadoRepository.GetAll();
            var estadoViewModelList = new List<EstadoViewModel>();

            foreach (var estado in estados)
                estadoViewModelList.Add(new EstadoViewModel(estado));

            ViewBag.estadoViewModelList = new MultiSelectList(estadoViewModelList, "EstadoId", "NomeEstado");
        }

    }
}

Prototipo.Curso.MVC.Web/Controllers/EstadoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prototipo.Curso.MVC.Dados.Interfaces;
using Prototipo.Curso.MVC.Dominio.Modelos;
using Prototipo.Curso.MVC.Web.Models;

namespace Prototipo.Curso.MVC.Web.Controllers
{
    public class EstadoController : Controller
    {
        private readonly IEstadoRepository _estadoRepository;

        public EstadoController(IEstadoRepository estadoRepository)
        {
            _estadoRepository = estadoRepository;
        }

        // GET: EstadoController
        public ActionResult Index()
        {
            var estados = _estadoRepository.GetAll();
            var estadoViewModelList = new List<EstadoViewModel>();

            foreach (var estado in estados)
                estadoViewModelList.Add(new EstadoViewModel(estado));

            return View(estadoViewModelList);
        }

        // GET: EstadoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EstadoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var estadoViewModel = new EstadoViewModel();
                var estado = estadoViewModel.ToEstado(collection);

                _estadoRepository.Create(estado);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EstadoController/Edit/5
        public ActionResult Edit(int id)
        {
            var estado = _estadoRepository.GetById(id);
            var estadoViewModel = new EstadoViewModel(estado);

            return View(estadoViewModel);
        }

        // POST: EstadoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var estadoViewModel = new EstadoViewModel();
                var estado = estadoViewModel.ToEstado(collection);

                _estadoRepository.Update(estado);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Prototipo.Curso.MVC.Web/Views/Cidade/Create.cshtml
@model Prototipo.Curso.MVC.Web.Models.CidadeViewModel

@{
    ViewData["Title"] = "Nova Cidade";
}

<h2>Nova Cidade</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeCidade" class="control-label">Cidade</label>
                <input asp-for="NomeCidade" class="form-control" />
                <span asp-validation-for="NomeCidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoId" class="control-label">Estado</label>
                @Html.DropDownList("EstadoId", (MultiSelectList)ViewBag.estadoViewModelList, new { @class = "form-control" })
                <span asp-validation-for="EstadoId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Enviar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prototipo.Curso.MVC.Web/Views/Cidade/Details.cshtml
@model Prototipo.Curso.MVC.Web.Models.CidadeViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h2>Detalhes Cidade</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Cidade
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeCidade)
        </dd>
        <dt class="col-sm-2">
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoViewModel.NomeEstado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { Id = Model.CidadeId }) |
    <a asp-action="Index">Voltar à listagem</a>
</div>

Prototipo.Curso.MVC.Web/Views/Cidade/Edit.cshtml
@model Prototipo.Curso.MVC.Web.Models.CidadeViewModel

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar Cidade</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input hidden asp-for="CidadeId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NomeCidade" class="control-label">Cidade</label>
                <input asp-for="NomeCidade" class="form-control" />
                <span asp-validation-for="NomeCidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoViewModel.NomeEstado" class="control-label">Estado Atual</label>
                <input disabled="disabled" asp-for="EstadoViewModel.NomeEstado" class="form-control" />
                <span asp-validation-for="EstadoViewModel.NomeEstado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoId" class="control-label"></label>
                @Html.DropDownList("EstadoId", (MultiSelectList)ViewBag.estadoViewModelList, new { @class = "form-control" })
                <span asp-validation-for="EstadoId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Prototipo.Curso.MVC.Web/Views/Cidade/Index.cshtml
@model IEnumerable<Prototipo.Curso.MVC.Web.Models.CidadeViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Listagem Cidades</h2>

<p>
    <a asp-action="Create">Nova Cidade</a> | <a asp-controller="Estado" asp-action="Index">Ir p/ Estado</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Cidade
            </th>
            <th>
                Estado
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeCidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstadoViewModel.NomeEstado)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { Id = item.CidadeId }) |
                    @Html.ActionLink("Detalhes", "Details", new { Id = item.CidadeId })
                </td>
            </tr>
        }
    </tbody>
</table>